services:
  database:
    image: postgres:16.3
    container_name: apartment-api-db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  app:
    build:
      context: .          # build Dockerfile อยู่ใน project folder
      dockerfile: Dockerfile
    container_name: apartment-api-app
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT : ${SERVER_PORT}
      SPRING_DATASOURCE_HOST: database
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_REGION: ${AWS_S3_REGION}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
    depends_on:
      - database